CREATE ROLE glamod_read PASSWORD '__INSERT_PASSWORD__' ;
ALTER ROLE glamod_read LOGIN ;
GRANT SELECT ON ALL TABLES IN SCHEMA lite TO glamod_read ;
GRANT USAGE ON SCHEMA lite TO glamod_read ;
GRANT SELECT ON ALL TABLES IN SCHEMA lite TO glamod_read ;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA lite TO glamod_read ;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA lite TO glamod_read ;
GRANT ALL ON ALL TABLES IN SCHEMA lite TO glamod_read ;
GRANT ALL ON ALL SEQUENCES IN SCHEMA lite TO glamod_read ;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA lite TO glamod_read ;

